### PR TITLE
adding StrategySystem to intakes

### PR DESCRIPTION
**Pull request by ben327**

### CODE REVIEW

**Comment by JacisNonsense** [comment]
There seems to be nothing in this PR :(

**Comment by ben327** [comment]
oh whoops, I PR'd from the wrong branch

**Comment by ben327** [comment]
do I need to make a new PR or can this be changed to my 'strategy-implementation' branch?

**Comment by JacisNonsense** [comment]
You'll have to make a new one, go ahead and close this one

**Pull request closed without merging**
